release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: cerebrux
    name: romie
  draft: true
  # You can change the name of the release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}}"
changelog:
  sort: asc
#  filters:
#    exclude:
#    - '^docs:'
#    - '^test:'
#    - Merge pull request
#    - Merge branch
#    - go mod tidy  
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386, arm
      - goos: windows
        goarch: arm, arm64
      - goos: freebsd
        goarch: arm64
      - goos: netbsd
        goarch: arm64
      - goos: dragonfly
        goarch: 386, arm, arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
